### PR TITLE
HRJS-30 HRJS-31 Domain mode testing and fix leaks

### PR DESCRIPTION
**Pull request by galderz**
* Remove old manual orchestration and instead create an Infinispan
  domain with all configurations for testing.
* Clean, untouched, domain and host configurations have been added for
  reference.
* Fix connection leak when switching between sites.
* Remove Haskell script for starting servers and instead use a simple
  bash script. Most of the work now done by the domain mode itself.
* Instead of CLI calls to reset statistics, or get cluster member
  information, use HTTP calls using 'request' package which is way
  faster.
* The reason for using 'request' package is because it makes it very
  easy to deal with digest based authorization required by server.

As a result of all these changes, JS client testsuite runs much faster! Before the changes it took about 1m45s and now it runs under 30s! :)

The domain configuration could be further simplified once [ISPN-7326](https://issues.jboss.org/browse/ISPN-7326) fixed.

### CODE REVIEW

**Comment by tristantarrant** [comment]
This doesn't work on Linux:

```
$ ./run-domain.sh 
mktemp: too few X's in template ‘infinispan-js-domain’
Terminated

```
According to mktemp's man page:

MKTEMP(1)                                              User Commands                                              MKTEMP(1)

NAME
       mktemp - create a temporary file or directory

SYNOPSIS
       mktemp [OPTION]... [TEMPLATE]

DESCRIPTION
       Create a temporary file or directory, safely, and print its name.  TEMPLATE must contain at least 3 consecutive 'X's
       in last component.  If TEMPLATE is not specified, use tmp.XXXXXXXXXX, and --tmpdir is implied.   Files  are  created
       u+rw, and directories u+rwx, minus umask restrictions.

**Comment by galderz** [comment]
Looking into it... :)

**Comment by galderz** [comment]
@tristantarrant Should work now :)

**Comment by tristantarrant** [comment]
Indeed, and very lovely it is. Merged !

**Pull request merged**
