### PR TITLE
Adding ESlint to the project

### PR DESCRIPTION
**Pull request by helio-frota**
* This commit adds eslint to the project using a configuration file based on opossum https://github.com/nodeshift/opossum library in which also apply linting to the JSDoc bits.
* This commit also removes the unused .jshintrc file.

### CODE REVIEW

**Comment by helio-frota** [comment]
This PR can be merged with no harm

Suggestions:
* After fix all the lint issues you can rename the npm script from `lint` to `pretest` so that it will run automatically every time you run the tests.
* You can add the `--fix` option to automatically try to fix some linting errors in the future

```
"lint": "eslint --fix --ignore-path .gitignore .",
```

**Comment by helio-frota** [comment]
This PR is related to https://github.com/infinispan/js-client/issues/81
but does not fixes the lint issues found, that is just the setup in a way that does not block the CI.

**Comment by helio-frota** [comment]
Once merged that will also help with the TS support effort https://github.com/infinispan/js-client/pull/93
as the linter is looking for proper JSDoc syntax.

**Comment by helio-frota** [comment]
@rigazilla @NeerajGartia21 I changed to a draft PR I think that is the best so you can decide to apply or not based in your PRs 

Also because the intention is not to make direct impact in the dev process flow of the team :+1:

**Comment by rigazilla** [comment]
merged thanks @helio-frota

**Pull request merged**
