### PR TITLE
HRJS-54 Add more checks at read time to check if read can happen

### PR DESCRIPTION
**Pull request by galderz**
The testsuite looks good. 

The SSL tests are failing due to expired certificates. I'll address that so that they're created on the fly instead of being committed.

### CODE REVIEW

**Comment by galderz** [comment]
I've created [HRJS-55](https://issues.jboss.org/browse/HRJS-55) to track the SSL expiration stuff. @tristantarrant Can you verify this?

**Comment by galderz** [comment]
Btw, I've squashed commits.

**Comment by galderz** [comment]
@tristantarrant I didn't see the first error locally. What version of Infinispan are you testing against?

**Comment by tristantarrant** [comment]
9.2.1.Final and 9.3.0.Alpha1

**Comment by tristantarrant** [comment]
Merged, thanks

**Pull request merged**
